### PR TITLE
Bug fixes and updates for the Jacko opcodes

### PR DESCRIPTION
**Pull request by gogins**
- Bumped C++ standard to 2020.
- Simplified port creation and connection code to eliminate "stack crashing" errors in normal use (at least, on Linux).
- Replaced somewhat low-level pthreads concurrency code with somewhat higher-level and easier to read standard C++ library code.
- Fixed bugs in Jacko's code for creating audio input ports and connecting them to Jack capture ports.
- Fixed a bug causing Csound to hang when handling 'e' score events used by some hosts to stop the Csound performance.
- Tested sending Csound score events to Jack MIDI playback ports using the `JackoNoteOut` opcode, i.e. sending notes from Csound to external MIDI synthesizers via Jack.
- Improved example/test CSD file `jacko_test.csd`.

### CODE REVIEW

**Comment by gogins** [comment]
It all seemed to build but took a looong time...

**Review by stekyne — APPROVED** [review]
Looks good to me

**Comment by stekyne** [comment]
Should this work on Windows? I notice it can't find the jack library but it does seem Jack works on that platform.

**Comment by gogins** [comment]
It should work on Windows, but I don't currently have a Windows computer to
test it. The test build in the pull request seemed to go through, though.

Regards,
Mike
-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
Thanks!

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Pull request merged**
